travis:
  secure:
    BINSTAR_TOKEN: PslSMcmfRlQgBajhVV0sCVtwIpXFvGt0YRWX1wDUKJvdQiDIZg7c+9UL7dWgRocq3uhQXMUh2ZlbV/9Pi5hqD1DCK+MY0b4t5PtoLg6obbNfHHVBGDR62KERHCeiUVhi700minHh5T5QV0XC5anc+RHHEiDmCblmgFzMLrCXrJr9gO+gJXXFRISwxHjMT65QQS1C8sIEsK/DP6lfADRl3zS+6TTxMRi7WkJOsHkldt7ZddxHZxSPukwRX9bbmYIg+I0nEHq2rcukJTdkI5oAcuUc26iMIS0YTnJkFwVQB1ld0R/jEP449dVsBBjwQmHUz+X66HpFk4kFBhbp8CZPPQU6+i9VczrN4aX2Khmb6uxbdE4PFNiJzIDeyA2PKm0Ig+T0LP/X1VKZZrUTYBRpEWKCzcHbdmLEfxNXtCas3phCn1Bfvex7cBwh/cYLOCwHyldR04Eo+IvIndw20VuZFiwUjHk3udTAxQ6kJa8J4TxGWx/umHImn3W+yPaHjWWMsZ6oyX5uRocBf56GLnxIBGz05SjXdWsNmIG61TXkzd5fTPsHwa6OpIAE6TuyKJBvSXEmtjt9zU1m7ZNf+5w5cZgz517vrhTQWdZjUASqR/4HGLAIvbhX+aU+4nSAPTx81HFsLhhXV4yEyAZzTFwTFjn50wLsJW4UUPv6e8OziZI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
