appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Fkn/4c3xhb7Os0AkwpPG4JvFLgGrtLKKIU8vpLUQzzXrKaJcMD9M44ASkmdNqN2yjaujlPxA+CVmnP2GNF/zfZpVPfoVbURmSXlSnoTI/Mjw3a3r0dOUZc1R+DJcjS7vsuu0yiiy/LDGMu/5Pii/gJl9ejX5NZ6TMEVDj0ZavVceIgmMXqWCF6S0OpMr7Ml4emnqly39wP/qUaV1TtfhWcbE2lC35pfjG//CeauN81ivjMLaXNzaofloDoglBkezv+BkSoNEefwte4BQ6cTY9mokrruiy7VxEQGKJMAhjVeCFRor2H7r/0z5cIjj2yU4AqrOG5+stet2YCYpAC0Q1zURMerrzW3SNE++tM7EeakGq5W2e7QFqxkpBOVtLGhn3mcVY56187xatsATtxUyXC54gc27yIystgJkiVCwRZcNmbyGtqfro1qQtIv3YjH6TGuXU5LPZSxYGhQXvQOd64c+7KrEMI31lOkeaWwuwFE8ZQ6RJQN+K5ZjFDmTpEBz1TN61olqmjdz4LHAKEgXrAt+on7SoztEqzLgMbDFxL319MtzszRdjHIKHkfvG2xZrbTamJObx8ZffAyIqWnEySvZ0q1OUCSZZiGPLjAUJojyzDOpHcKchh0PniBaPg+sMrMAgdHuiJzd4l94InF9wM9aWpfqcppd74sXWbC/s4U=}
conda_forge_output_validation: true
